#!/usr/bin/env bash

SERVER_DIR=/usr/src/app/server/dynamodb-titan100-storage-backend-1.0.0-hadoop1

envsubst < /usr/src/app/dynamodb-local.properties.template > $SERVER_DIR/conf/gremlin-server/dynamodb-local.properties
envsubst < /usr/src/app/gremlin-server-local.yaml.template > $SERVER_DIR/conf/gremlin-server/gremlin-server-local.yaml

if [ -z "$1" ]
then
  exec $SERVER_DIR/bin/gremlin-server.sh $SERVER_DIR/conf/gremlin-server/gremlin-server-local.yaml
elif [ "$1" == "console" ]
then
  exec $SERVER_DIR/bin/gremlin.sh
else
  exec $SERVER_DIR/$1
fi
